"""Structured transcription of Music_Producers_Genre_Guide.pdf."""

from __future__ import annotations

from typing import Any

BOOK = {
    "title": "The Music Producer's Complete Genre Guide",
    "subtitle": "How to Create Music Across Genres — From First Sound to Finished Track",
    "edition": "Desktop Reference Edition • Comprehensive Handbook",
    "pages": 49,
    "source_path": r"C:\Users\Box One\Desktop\Music_Producers_Genre_Guide.pdf",
    "tags": [
        "production blueprints",
        "mixing notes",
        "arrangement maps",
        "BPM / feel / keys",
    ],
    "parts": [
        "I Foundations (1–6)",
        "II Urban & Black American Traditions (7–12)",
        "III Electronic Dance Music (13–20)",
        "IV Pop & Mainstream (21–24)",
        "V Rock, Alternative & Metal (25–27)",
        "VI Global, Roots & Acoustic (28–33)",
        "VII Niche, Hybrid & Internet-Era (34–37)",
        "VIII Reference Systems (38–40)",
    ],
}

FOUNDATIONS: dict[str, dict[str, Any]] = {
    "mindset": {
        "section": 1,
        "name": "Producer mindset & workflow",
        "summary": (
            "Producer owns sonic identity, arrangement, performance direction, emotional arc. "
            "Genre literacy = knowing listener contracts, not rigid laws."
        ),
        "workflow": [
            "Reference 2–4 commercial tracks (loudness, drum density, vocal placement, sidechain)",
            "Set tempo & groove/swing grid first",
            "Build 4–8 bar core loop (drums + bass + hook) that already feels like the genre",
            "Map arrangement (song form or dance intro–build–drop–break)",
            "Sound design pass: replace placeholders, intentional layering",
            "Vocal/lead focus: carve space early if vocals exist",
            "Mix in context while arrangement still flexible",
            "Print, rest, revise against references",
        ],
        "tip": "Finish more tracks than you perfect; fluency = 20 average songs in a style.",
    },
    "theory": {
        "section": 2,
        "name": "Core music theory for production",
        "summary": "Practical keys/modes, chords, voice leading, rhythm/swing/syncopation for DAW decisions.",
        "modes_for_producers": {
            "Dorian": "minor + raised 6 — groovy/soulful",
            "Phrygian": "flat 2 — Spanish/metal/dark electronic",
            "Mixolydian": "major + flat 7 — bluesy/rock",
            "Lydian": "raised 4 — dreamy/cinematic",
            "Aeolian": "natural minor — default sad/modern",
            "Harmonic minor": "raised 7 — metal/classical/EDM tension",
        },
        "chords": [
            "Triads; 7ths (maj7/m7/dom7); extensions 9/11/13",
            "Sus2/4; power chords for distortion clarity",
            "Modal interchange bVI/bVII/iv into major (pop/rock)",
        ],
        "rhythm": "4/4 default; subdivision + swing define genre as much as BPM; syncopation = funk/Latin/Afrobeats/R&B soul",
    },
    "sound_design": {
        "section": 3,
        "name": "Sound design basics",
        "chain": ["Source", "Tone shape (filter/distort)", "Dynamics (ADSR)", "Motion (LFO/seq)", "Space (delay/verb)", "Glue (bus sat/comp)"],
        "sampling": "Chop to transient, pitch to key, stretch, layer, resample own synths; clear samples for commercial release",
    },
    "drums": {
        "section": 4,
        "name": "Drums, groove & rhythm foundations",
        "pillars": ["Kick (weight/length/click; tune to key)", "Snare/clap (backbeat layers + ghosts)", "Hats/cymbals (energy)", "Percussion (cultural identity)"],
        "humanize": "Groove templates, velocity, ±5–15 ms nudge, round-robin samples; don't over-humanize machine aesthetics",
    },
    "arrangement": {
        "section": 5,
        "name": "Arrangement architecture",
        "energy_tools": [
            "Add/remove layers; filter open/close",
            "Drum density (half-time vs double-time)",
            "Risers, reverse cymbals, impacts, silence before drops",
            "Vocal chops as transitions",
            "Key lift sparingly; breakdown then rebuild",
        ],
        "forms": {
            "song": "verse–pre–chorus–chorus + bridge",
            "dance": "DJ intro/outro, builds, drops",
            "hip_hop": "loops marked by vocal density/ad-libs/drops",
        },
    },
    "mix_master": {
        "section": 6,
        "name": "Mixing & mastering by genre context",
        "order": [
            "Gain staging (−6 to −12 dBFS peaks early)",
            "High-pass non-bass carefully",
            "Fader balance first",
            "EQ subtract then character",
            "Compression (glue/parallel/peak)",
            "Spatial FX; filter verbs/delays",
            "Automation rides",
            "Master: gentle EQ, limiter, ~−1 dBTP streaming headroom",
        ],
        "tip": "Kick–bass is the #1 genre-defining mix problem — complementary EQ, sidechain, or frequency splitting.",
    },
}

# Genre blueprints (sections 7–37)
GENRES: dict[str, dict[str, Any]] = {
    "boom_bap": {
        "id": 7,
        "name": "Boom Bap & Classic Hip-Hop",
        "tagline": "Head-nod golden-era foundation",
        "bpm": "85–98 (sweet spot ~90–94)",
        "feel": "Swung/light swung 16ths; hard kick/snare boom–bap",
        "keys": "Minor common; samples dictate",
        "core": ["Sampled/SP kits", "chopped loops", "bass", "scratches", "raw vocals"],
        "mix_vibe": "Mid-forward, punchy drums, not ultra-loud modern smash",
        "production": [
            "Snare on 2 & 4; ghost snares/rims for pocket",
            "Chop soul/jazz/funk; pitch/filter/saturate",
            "MPC-style swing and velocity",
            "Leave space for vocals; dusty texture valued",
        ],
        "mix_notes": [
            "Drums slightly louder vs bed than modern pop",
            "HP samples ~100–200 Hz if separate bass",
            "Parallel drum compression; short plate on vocal",
            "Avoid over-limiting snare snap",
        ],
        "tip": "Print sample through tape/console emu, then re-chop.",
    },
    "trap": {
        "id": 8,
        "name": "Trap & Modern Hip-Hop",
        "tagline": "808s, hat rolls, dark melodies, streaming low end",
        "bpm": "130–160 half-time feel (or 70–90 straight)",
        "feel": "Snare on 3; rapid hat rolls; sliding 808s",
        "keys": "Minor / harmonic minor / Phrygian",
        "core": ["808", "snare/clap", "hat rolls", "dark bells/pads", "ad-libs"],
        "mix_vibe": "Loud, sub-heavy, vocal-forward, mono lows",
        "production": [
            "Start ~140 BPM; snare on beat 3",
            "808 as bassline with glide/portamento; may double as kick",
            "Hat 1/8–1/64 rolls with pitch automation",
            "Arrangement: intro–verse–hook–verse–hook–bridge–final",
        ],
        "mix_notes": [
            "Mono sub <~120 Hz; saturate 808 for small speakers",
            "Duck pads to kick/808; serial vocal compression",
            "Carve 200–400 Hz if 808 fights vocal",
        ],
        "tip": "Program 808 and vocal melody to leave pocket for each other.",
    },
    "drill": {
        "id": 9,
        "name": "Drill (UK & US)",
        "tagline": "Sliding 808s, menacing patterns, street energy",
        "bpm": "UK ~138–146 | US ~60–70 half-time / ~130–145",
        "feel": "Stutter hats, sharp snares, sliding 808s",
        "keys": "Very dark minor; sparse harmony",
        "core": ["808 slides", "cold piano/leads", "aggressive vocal", "drill snares"],
        "mix_vibe": "Hard-hitting, cold, vocal center",
        "production": [
            "Long 808 glides; chromatic approaches; silence in pattern",
            "Sharper/syncopated snares vs generic trap",
            "Cold piano/strings/desaturated bells",
            "UK vs US: study regional bounce and 808 writing separately",
        ],
        "tip": "Write 808 after rough vocal rhythm sketch — converse with flow.",
    },
    "rnb": {
        "id": 10,
        "name": "R&B / Contemporary R&B",
        "tagline": "Groove, harmonic color, vocal intimacy",
        "bpm": "60–90 ballad | 90–115 mid | up to 115–130",
        "feel": "Pocketed/swung; ghost notes; syncopated bass",
        "keys": "7ths/9ths/11ths; modal interchange",
        "core": ["Bass/808 hybrid", "Rhodes/piano", "guitars", "airy drums", "stacked vocals"],
        "mix_vibe": "Vocal throne, warm mids, controlled sub",
        "production": [
            "Extended chords + smooth voice leading",
            "Kick syncopates around vocal; soft layered snare/clap",
            "Electric bass slides + optional 808 sub",
            "Intimate dry verses; wider wetter choruses",
        ],
        "tip": "Automate closer-mic verse feel vs open chorus space.",
    },
    "soul_gospel": {
        "id": 11,
        "name": "Soul, Neo-Soul & Gospel",
        "tagline": "Human feel, choir power, organ/piano truth",
        "bpm": "70–100+ (uptempo gospel higher)",
        "feel": "Behind-the-beat pocket; swing; dynamics",
        "keys": "Gospel secondary dominants; soul cadences",
        "core": ["Piano/organ", "choir/BGVs", "live drums/bass", "tambourine"],
        "mix_vibe": "Warm, wide vocals, natural rooms, not over-squashed",
        "production": [
            "B3/Leslie, SATB choir thinking, dynamic testimony→praise arc",
            "Neo-soul: imperfect timing, Rhodes, jazz chords, small-room intimacy",
            "Resist over-quantize; gentle bus glue",
        ],
    },
    "funk_disco": {
        "id": 12,
        "name": "Funk & Disco",
        "tagline": "Pocket, syncopation, bass as lead",
        "bpm": "Funk 90–115 | Disco 110–130 (~118–124 classic)",
        "feel": "16th syncopation; chicken-scratch guitar; interlocking parts",
        "keys": "Dom7/Mixolydian vamps; disco major joy",
        "core": ["Bass heroics", "tight drums", "rhythm guitar", "horns", "disco strings"],
        "mix_vibe": "Punchy, danceable, clear mid rhythm, mono kick/bass",
        "production": [
            "Funk: emphasize the one; ghost notes; negative space between parts",
            "Disco: four-on-floor, octave bass, long intros/breaks",
            "Nu-disco: sidechain + cleaner polish",
        ],
        "tip": "Slight timing push/pull — perfect quantize kills sweat.",
    },
    "house": {
        "id": 13,
        "name": "House (Deep, Tech, Progressive, Future)",
        "tagline": "Four-on-the-floor soul of the dancefloor",
        "bpm": "118–130 (classic ~120–125; tech often 124–128)",
        "feel": "Kick every beat; offbeat open hats; groovy bass",
        "keys": "Minor common; deep jazzier; future brighter",
        "core": ["Kick", "clap 2/4", "hats", "bass", "chords/stabs", "vocals/chops"],
        "mix_vibe": "Club low end, wide perc, clear mid hooks",
        "production": [
            "Universal grid: kick 1–4, clap 2/4, open hat on ands",
            "Sidechain bass to kick nearly mandatory modern",
            "DJ form: 16–32 bar intro/outro; phrase in 8/16/32",
            "Substyles: deep / tech / progressive / future / afro house",
        ],
        "tip": "Mark phrase lengths in 8/16/32 — dancers feel them.",
    },
    "techno": {
        "id": 14,
        "name": "Techno",
        "tagline": "Hypnosis, functional design, relentless pulse",
        "bpm": "125–140 (peak often 130–135)",
        "feel": "Four-on-floor; machine precision; long evolving forms",
        "keys": "Minor/modal; sometimes textural/atonal",
        "core": ["Powerful kick", "hats", "metallic perc", "drones", "acid/sparse motifs"],
        "mix_vibe": "Mono kick, controlled mids, club translation",
        "production": [
            "Kick must carry 6+ minutes; complementary bass pulse",
            "Slow filter automation; subtractive arrangement",
            "Industrial samples, FM metals, noise beds",
        ],
        "tip": "Automate one parameter per long section — art of patient change.",
    },
    "trance": {
        "id": 15,
        "name": "Trance & Progressive Trance",
        "tagline": "Supersaws, tension/release, uplifting journeys",
        "bpm": "130–145 (~138 uplifting)",
        "feel": "Four-on-floor; rolling bass; big builds",
        "keys": "Emotional minor; major lifts",
        "core": ["Supersaws", "arps", "pads", "snare rolls", "uplifting leads"],
        "mix_vibe": "Wide leads, clean sub, shiny highs without fatigue",
        "production": [
            "Unison supersaws + filter envelopes",
            "Breakdown strip → rebuild drop",
            "Earn the lead; don't crowd midrange",
        ],
    },
    "dnb": {
        "id": 16,
        "name": "Drum & Bass / Jungle",
        "tagline": "Amen history, 170 energy, sub + reese science",
        "bpm": "170–178",
        "feel": "Fast breaks; half-time bass feel often",
        "keys": "Minor; liquid more harmonic; neuro SD-led",
        "core": ["Breaks", "sub", "reese/neuro bass", "pads (liquid)"],
        "mix_vibe": "Sub clarity, mid-bass character, DJ-friendly drops",
        "production": [
            "Slice/rearrange breaks; layer one-shots; parallel comp",
            "Split sub (clean mono) vs mid bass (reese/neuro)",
            "Substyles: liquid, jump-up, neurofunk, jungle revival",
        ],
        "tip": "At 174 BPM arrange in 8/16 bar phrases + automation.",
    },
    "dubstep": {
        "id": 17,
        "name": "Dubstep & Riddim",
        "tagline": "Wobbles, drops, half-time weight, SD as star",
        "bpm": "138–150 half-time (snare on 3)",
        "feel": "Space/silence as weapons; massive drop contrast",
        "keys": "Minor/dark; riff-based",
        "core": ["Heavy kick/snare", "growls/wobbles", "reese", "vocal chops"],
        "mix_vibe": "Huge drop loudness; clean sub; controlled mid aggression",
        "production": [
            "Contrast: sparse verse → bass-weight drop",
            "2–4 unique bass patches call-and-response",
            "Layer sub + mid growl + top click; multiband distort mids only",
            "Riddim: hypnotic minimal motifs",
        ],
        "tip": "Weak drop = contrast/mid-bass clarity, not more plugins.",
    },
    "uk_garage_grime": {
        "id": 18,
        "name": "UK Garage, 2-Step & Grime",
        "tagline": "Shuffled drums, skippy swing, MC space",
        "bpm": "UKG ~128–138 | Grime ~135–140",
        "feel": "Skipped kicks; syncopated snares; swung hats",
        "keys": "Minor common; garage can be soulful",
        "core": ["Shuffle drums", "deep bass", "pitched vocals (garage)", "sparse cold riddims (grime)"],
        "mix_vibe": "Bouncy; clear mid bass; vocal/MC intelligibility",
        "production": [
            "2-step: remove kicks from 4/4 so pattern skips",
            "Garage: melodic bass, stabs, pitched vocal chops",
            "Grime: leave space for MC; cold simple loops; bold silence",
        ],
    },
    "hardstyle": {
        "id": 19,
        "name": "Hardstyle / Hard Dance",
        "tagline": "Reverse bass, screeches, hard kicks",
        "bpm": "150–160+",
        "feel": "Driving kicks; euphoric or raw extremes",
        "keys": "Minor anthems; dramatic leads",
        "core": ["Designed distorted kick", "reverse bass", "screeches", "climaxes"],
        "mix_vibe": "Kick is king; mid lead clarity",
        "production": [
            "Design kicks (body, distortion, pitch env, clipping)",
            "Reverse bass ducks around kick",
            "Multiple festival climaxes",
        ],
    },
    "ambient_idm": {
        "id": 20,
        "name": "Ambient, Downtempo & IDM",
        "tagline": "Space, texture, anti-drop listening music",
        "bpm": "Ambient free/60–100 | Downtempo 70–100 | IDM variable",
        "feel": "Atmosphere over club function",
        "keys": "Modal/sparse/drones",
        "core": ["Pads", "field recordings", "granular", "gentle/glitch perc"],
        "mix_vibe": "Dynamic range, wide stereo, quiet detail",
        "production": [
            "Long verbs/convolution; granular clouds",
            "IDM: non-repeating drums, glitch, odd structures",
            "Avoid over-limiting",
        ],
        "tip": "Introduce one new element every 30–60 seconds.",
    },
    "pop": {
        "id": 21,
        "name": "Contemporary Pop",
        "tagline": "Hooks, contrast, vocal production",
        "bpm": "90–130 (ballads slower; dance-pop higher)",
        "feel": "Clean quantize or light human; chorus lift",
        "keys": "Accessible I–V–vi–IV family",
        "core": ["Lead vocal", "BGV stacks", "tight drums", "bass", "hook motif"],
        "mix_vibe": "Vocal #1, competitive loudness, mono-compatible core",
        "production": [
            "Short intro; verse low / pre tension / chorus fullest",
            "Comp, tune, double stacks, delay throws, de-ess before brighten",
            "If chorus not bigger, remove verse elements (relative contrast)",
        ],
        "tip": "Chorus contrast is relative — subtract verse layers.",
    },
    "kpop": {
        "id": 22,
        "name": "K-Pop Production Language",
        "tagline": "Maximal sections; hybrid medleys in one song",
        "bpm": "Wide; feel changes mid-track",
        "feel": "Tight timing; dramatic switches",
        "keys": "Pop-accessible + EDM lifts/modulations",
        "core": ["Multiple hooks", "rap sections", "dance breaks", "hybrid orchestration"],
        "mix_vibe": "Ultra polished, wide, group-vocal clarity",
        "production": [
            "Produce sections as mini-genres under shared aesthetic",
            "Consistent vocal chain; cinematic transitions",
        ],
    },
    "hyperpop": {
        "id": 23,
        "name": "Hyperpop & PC Music Influences",
        "tagline": "Maximal brightness, exaggerated tuning",
        "bpm": "Often 140+ or glitchy midtempos",
        "feel": "Over-quantized or chaotic edits",
        "keys": "Bright major or emotional minor + extreme SD",
        "core": ["Hard-tuned vocals", "metallic leads", "glitch", "ironic clichés"],
        "mix_vibe": "Loud, bright, saturated, intentionally too much",
        "production": [
            "Extreme autotune/formants; sidechain as style",
            "Bitcrush/clipping; embrace artifacts",
        ],
    },
    "synthwave": {
        "id": 24,
        "name": "Synthwave / Retrowave / Outrun",
        "tagline": "1980s fantasy; neon nostalgia; driving arps",
        "bpm": "80–120; outrun often ~100–118",
        "feel": "Steady groove; gated snares",
        "keys": "Minor night-drive; major uplifting retro",
        "core": ["Analog bass", "saws", "FM bells", "gated snare", "arps", "pads"],
        "mix_vibe": "Warm yet shiny; tape/chorus; cinematic width",
        "production": [
            "LINN/DMX/808–909 aesthetics; Juno-style bass; DX7 bells",
            "Darksynth more aggressive; outrun driving motion",
        ],
        "tip": "Genre is as visual as musical — reference 80s film scores.",
    },
    "rock": {
        "id": 25,
        "name": "Rock & Indie Rock",
        "tagline": "Guitars as narrative; human performance",
        "bpm": "100–160; indie often midtempo",
        "feel": "Live push/pull; backbeat; riff-driven",
        "keys": "Power chords; indie diatonic/alt harmony",
        "core": ["E guitars", "bass", "live/hybrid drums", "vocals"],
        "mix_vibe": "Guitar/vocal balance; mono kick/snare/bass",
        "production": [
            "Double-track rhythm guitars L/R; DI+amp",
            "Indie: texture, intimate vocals, era-defining reverb",
        ],
    },
    "punk": {
        "id": 26,
        "name": "Punk & Post-Punk",
        "tagline": "Speed, attitude, angular grooves",
        "bpm": "Punk 160–220 | Post-punk midtempo danceable darkness",
        "feel": "Driving eighths; post-punk bass-led",
        "keys": "Simple; modal post-punk vamps",
        "core": ["Distorted guitars", "prominent bass", "raw drums", "urgent vocals"],
        "mix_vibe": "Rawer midrange aggression; don't over-polish (unless pop-punk)",
        "production": [
            "Punk: energy over polish; gang vocals",
            "Post-punk: melodic bass lead, chorus/delay guitars, danceable darkness",
        ],
    },
    "metal": {
        "id": 27,
        "name": "Metal (Modern & Substyles)",
        "tagline": "Precision, weight, guitar tone science",
        "bpm": "60 doom to 220+ extreme",
        "feel": "Chugs, double kick, breakdowns, blasts",
        "keys": "Minor/Phrygian/harmonic minor; low-tuned modality",
        "core": ["High-gain guitars", "tight DI bass", "hybrid drums", "aggressive vocals"],
        "mix_vibe": "Guitar clarity + heavy low end; kick/guitar carve",
        "production": [
            "DI + amp sim; quad-track rhythms phase-aligned",
            "Carve kick vs guitar 100–200 Hz; sample reinforce drums",
            "Substyles: thrash, death/black, metalcore/djent, doom",
        ],
    },
    "jazz": {
        "id": 28,
        "name": "Jazz (for Producers)",
        "tagline": "Improvisation space, swing, sophisticated harmony",
        "bpm": "Ballad 60–80 | medium 100–140 | uptempo higher",
        "feel": "Swing eighths; ride language; interactive pocket",
        "keys": "ii–V–I language; extensions; substitutions",
        "core": ["Acoustic kit", "upright/electric bass", "piano/keys", "horns/voice", "space for solos"],
        "mix_vibe": "Natural dynamics; room; minimal squash",
        "production": ["Leave solo space", "realistic kits/rooms", "don't over-quantize swing"],
    },
    "country": {
        "id": 29,
        "name": "Country & Americana",
        "tagline": "Story-first; twang; modern pop hybrids",
        "bpm": "70–140",
        "feel": "Straight or gentle swing; train beats",
        "keys": "Accessible major/minor; story harmony",
        "core": ["Acoustic/electric guitars", "pedal steel/fiddle vocabulary", "vocal story", "tight rhythm section"],
        "mix_vibe": "Vocal-forward storytelling; modern country may borrow pop polish",
    },
    "reggae_dub": {
        "id": 30,
        "name": "Reggae, Dancehall & Dub",
        "tagline": "Offbeat skank, heavy bass, space as rhythm",
        "bpm": "Reggae ~70–90 (or double-time feel) | Dancehall often higher energy",
        "feel": "One-drop/rockers/steppers; offbeat guitar/keys",
        "keys": "Minor/major vamps; modal simplicity",
        "core": ["Bass culture", "skank", "drums", "toasting/vocals", "dub FX"],
        "mix_vibe": "Bass weight; space; delay throws (dub)",
        "production": ["Dub: strip, FX send performances, spring/tape delays"],
    },
    "latin": {
        "id": 31,
        "name": "Latin: Reggaeton, Salsa, Bachata, Latin Trap",
        "tagline": "Dembow engine, clave awareness",
        "bpm": "Reggaeton ~85–100 | Salsa high pulse energy | Bachata mid romantic | Latin trap trap-hybrid",
        "feel": "Dembow for reggaeton; clave for Afro-Cuban; romantic bachata guitar",
        "keys": "Minor/major dance & romance palettes",
        "core": ["Dembow drums", "percussion", "bass", "vocals", " dembow+808 hybrids in Latin trap"],
        "mix_vibe": "Club-ready low end for reggaeton/trap; acoustic clarity for salsa/bachata",
    },
    "afrobeats": {
        "id": 32,
        "name": "Afrobeats, Amapiano & African Pop",
        "tagline": "Log drums, joyful groove, percussion abundance",
        "bpm": "Afrobeats ~95–115 | Amapiano ~110–115",
        "feel": "Syncopated, dancing, percussion-forward",
        "keys": "Major/minor pop; groove over dense harmony often",
        "core": ["Log drums (amapiano)", "shakers/perc", "bass", "melodic hooks", "vocals"],
        "mix_vibe": "Clear perc, warm bass, open vocals, global fusion polish",
    },
    "cinematic": {
        "id": 33,
        "name": "Classical / Cinematic / Orchestral Hybrid",
        "tagline": "Themes, orchestration, trailer hybrids",
        "bpm": "Flexible; trailer pulses common",
        "feel": "Rubato or epic rigid pulses",
        "keys": "Functional + modal cinematic harmony",
        "core": ["Orchestral libraries", "hybrid percussion", "synths", "themes/motifs"],
        "mix_vibe": "Wide, dynamic (or trailer-loud hybrids), depth layering",
        "production": ["Mockup expression CCs", "hybrid trailer brass/perc + orchestra"],
    },
    "lofi": {
        "id": 34,
        "name": "Lo-fi Hip-Hop",
        "tagline": "Study beats, dusty comfort, imperfect beauty",
        "bpm": "70–95",
        "feel": "Swung lazy pocket; vinyl texture",
        "keys": "Jazz/soul chords; mellow minor/major7 colors",
        "core": ["Dusty drums", "chops/keys", "soft bass", "vinyl noise"],
        "mix_vibe": "Limited bandwidth intentional; soft tops; unobtrusive",
        "production": ["Wow/flutter, LP filters, imperfect timing as aesthetic"],
    },
    "phonk": {
        "id": 35,
        "name": "Phonk & Drift Phonk",
        "tagline": "Cowbells, Memphis DNA, distorted 808s",
        "bpm": "Often ~130–160 half-time; drift variants",
        "feel": "Aggressive bounce; cowbell ostinatos",
        "keys": "Dark minor; menacing loops",
        "core": ["Cowbell", "distorted 808", "Memphis vocal samples/aesthetic", "hard drums"],
        "mix_vibe": "Loud, distorted low-mid character, car-system energy",
    },
    "cloud_rap": {
        "id": 36,
        "name": "Cloud Rap & Emo Rap Textures",
        "tagline": "Airy atmospheres, emotional vocals",
        "bpm": "Trap-adjacent; spacious half-time",
        "feel": "Floaty, less hard-quantized aggression",
        "keys": "Emotional minor; ethereal pads",
        "core": ["Airy pads", "soft/trap drums", "emotive vocals", "reverb space"],
        "mix_vibe": "Wide wet spaces; vocal emotion over hardness",
    },
    "experimental": {
        "id": 37,
        "name": "Experimental / Genre-Bending Strategy",
        "tagline": "Fusions without random mess",
        "bpm": "Whatever serves the idea",
        "feel": "Defined by your hybrid contract",
        "keys": "Any — state the harmonic language",
        "core": ["Clear primary genre contract + 1–2 borrowed features"],
        "mix_vibe": "Coherent world; intentional rules",
        "production": [
            "Pick a base genre contract (drums/bass/mix)",
            "Borrow limited foreign elements",
            "Keep one consistent production aesthetic so fusion reads as design not chaos",
        ],
    },
}

# Reference part summaries
REFERENCES = {
    38: "BPM / Key / Drum Map Quick Reference — starting grids, not prisons",
    39: "Plugin & Stock-Tool Cookbook — stock + third-party roles by genre family",
    40: "Finishing Checklist (Any Genre) — export, references, mono, multiple systems, TP headroom",
    "glossary": "Genre is shared language; learn fluently enough to speak without accent — or break grammar on purpose",
}


def list_genres() -> list[str]:
    return list(GENRES.keys())


def get_genre(name: str) -> dict[str, Any]:
    key = name.strip().lower().replace(" ", "_").replace("-", "_").replace("&", "and").replace("/", "_")
    aliases = {
        "boom_bap": "boom_bap",
        "classic_hip_hop": "boom_bap",
        "hiphop": "trap",
        "hip_hop": "trap",
        "modern_hip_hop": "trap",
        "uk_drill": "drill",
        "r_and_b": "rnb",
        "r&b": "rnb",
        "neo_soul": "soul_gospel",
        "gospel": "soul_gospel",
        "soul": "soul_gospel",
        "disco": "funk_disco",
        "funk": "funk_disco",
        "deep_house": "house",
        "tech_house": "house",
        "edm": "house",
        "drum_and_bass": "dnb",
        "jungle": "dnb",
        "neurofunk": "dnb",
        "riddim": "dubstep",
        "ukg": "uk_garage_grime",
        "garage": "uk_garage_grime",
        "grime": "uk_garage_grime",
        "2_step": "uk_garage_grime",
        "hard_dance": "hardstyle",
        "ambient": "ambient_idm",
        "idm": "ambient_idm",
        "downtempo": "ambient_idm",
        "k_pop": "kpop",
        "pc_music": "hyperpop",
        "retrowave": "synthwave",
        "outrun": "synthwave",
        "indie": "rock",
        "post_punk": "punk",
        "metalcore": "metal",
        "djent": "metal",
        "reggaeton": "latin",
        "salsa": "latin",
        "bachata": "latin",
        "amapiano": "afrobeats",
        "african_pop": "afrobeats",
        "orchestral": "cinematic",
        "trailer": "cinematic",
        "lo_fi": "lofi",
        "lo-fi": "lofi",
        "drift_phonk": "phonk",
        "emo_rap": "cloud_rap",
        "fusion": "experimental",
        "dancehall": "reggae_dub",
        "dub": "reggae_dub",
        "reggae": "reggae_dub",
        "americana": "country",
    }
    key = aliases.get(key, key)
    if key not in GENRES:
        for k, v in GENRES.items():
            if key in k or key in v["name"].lower():
                return v
        raise KeyError(f"Unknown genre '{name}'. Try: {', '.join(list_genres()[:12])}…")
    return GENRES[key]


def get_foundation(name: str) -> dict[str, Any]:
    key = name.strip().lower().replace(" ", "_")
    aliases = {
        "workflow": "mindset",
        "producer": "mindset",
        "music_theory": "theory",
        "synths": "sound_design",
        "design": "sound_design",
        "groove": "drums",
        "rhythm": "drums",
        "arrange": "arrangement",
        "mixing": "mix_master",
        "mastering": "mix_master",
        "mix": "mix_master",
    }
    key = aliases.get(key, key)
    if key not in FOUNDATIONS:
        raise KeyError(f"Unknown foundation '{name}'. Try: {', '.join(FOUNDATIONS)}")
    return FOUNDATIONS[key]
